// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiDomainTradingEngine.Data;

#nullable disable

namespace Multi_Domain_Trading_Engine.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260225002751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Corporation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoreSectorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffixes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoreSectorId");

                    b.ToTable("Corporations");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Wallet", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorporationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimarySector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValuationGrade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Corporation", b =>
                {
                    b.HasOne("Sector", "CoreSector")
                        .WithMany("CorporationsWithThisCore")
                        .HasForeignKey("CoreSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreSector");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Inventory", b =>
                {
                    b.HasOne("MultiDomainTradingEngine.Entities.Corporation", "Company")
                        .WithMany("Inventories")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Wallet", b =>
                {
                    b.HasOne("MultiDomainTradingEngine.Entities.Corporation", "Company")
                        .WithOne("Wallet")
                        .HasForeignKey("MultiDomainTradingEngine.Entities.Wallet", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Sector", b =>
                {
                    b.HasOne("MultiDomainTradingEngine.Entities.Corporation", null)
                        .WithMany("AdjacentSectors")
                        .HasForeignKey("CorporationId");
                });

            modelBuilder.Entity("MultiDomainTradingEngine.Entities.Corporation", b =>
                {
                    b.Navigation("AdjacentSectors");

                    b.Navigation("Inventories");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Sector", b =>
                {
                    b.Navigation("CorporationsWithThisCore");
                });
#pragma warning restore 612, 618
        }
    }
}
